# Generated by Django 3.1.2 on 2020-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='receipt',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
