# Generated by Django 3.1.2 on 2020-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=20)),
                ('admin_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QR_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=20)),
            ],
        ),
    ]
