# Generated by Django 3.1.2 on 2020-10-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_admin_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='qr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.qr_code'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
