# Generated by Django 3.1.2 on 2020-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201008_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
