# Generated by Django 3.1.2 on 2020-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201015_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipt'),
        ),
    ]
